CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    username VARCHAR(64) NOT NULL COMMENT '用户名',
    email VARCHAR(128) NOT NULL COMMENT '邮箱',
    password_hash VARCHAR(128) NOT NULL COMMENT '密码哈希',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1-正常，2-锁定，3-禁用',
    account_type TINYINT NOT NULL DEFAULT 1 COMMENT '账号类型：1-个人，2-企业',
    last_login_time DATETIME DEFAULT NULL COMMENT '最后登录时间',
    last_login_ip VARCHAR(45) DEFAULT NULL COMMENT '最后登录IP',
    failed_attempts INT NOT NULL DEFAULT 0 COMMENT '失败尝试次数',
    locked_until DATETIME DEFAULT NULL COMMENT '锁定截止时间',
    locale VARCHAR(10) NOT NULL DEFAULT 'en_US' COMMENT '语言偏好',
    timezone VARCHAR(40) NOT NULL DEFAULT 'UTC' COMMENT '时区',
    date_format VARCHAR(20) NOT NULL DEFAULT 'yyyy-MM-dd' COMMENT '日期格式',
    time_format VARCHAR(20) NOT NULL DEFAULT 'HH:mm:ss' COMMENT '时间格式',
    currency VARCHAR(3) NOT NULL DEFAULT 'USD' COMMENT '货币单位',
    region VARCHAR(10) DEFAULT NULL COMMENT '地区',
    tenant_id VARCHAR(32) NOT NULL COMMENT '租户ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_username_tenant (username, tenant_id),
    UNIQUE KEY uk_email_tenant (email, tenant_id),
    KEY idx_status (status),
    KEY idx_locale (locale),
    KEY idx_region (region),
    KEY idx_account_type (account_type),
    KEY idx_tenant (tenant_id),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表'; 