server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test_route
          uri: http://localhost:8081
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
      config:
        server-addr: localhost:8848
        namespace: dev
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.helix.dove: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 