version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dove-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NACOS_SERVER=nacos-server:8848
      - NACOS_NAMESPACE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - nacos-server
    networks:
      - dove-network

  redis:
    image: redis:7.2-alpine
    container_name: dove-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dove-network

  nacos-server:
    image: nacos/nacos-server:v2.3.0
    container_name: dove-nacos
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_NAME=nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    networks:
      - dove-network

  mysql:
    image: mysql:8.0
    container_name: dove-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dove-network

volumes:
  redis-data:
  mysql-data:

networks:
  dove-network:
    driver: bridge 