apiVersion: v1
kind: ConfigMap
metadata:
  name: dove-api-gateway-config
  namespace: dove
data:
  application.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: dove-api-gateway
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: prod_route
              uri: lb://prod-service
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: defaultCircuitBreaker
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          show-details: never
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        root: WARN
        com.helix.dove: INFO 