apiVersion: v1
kind: Service
metadata:
  name: dove-api-gateway
  namespace: dove
  labels:
    app: dove-api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: dove-api-gateway 