apiVersion: v1
kind: Service
metadata:
  name: dove-auth-service
  labels:
    app: dove-auth
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: dove-auth 