region:
  # 区域信息
  regions:
    # 亚太地区
    ap:
      name: Asia Pacific
      datacenters:
        - id: ap-east-1
          name: Hong Kong
          priority: 1
          weight: 100
        - id: ap-southeast-1
          name: Singapore
          priority: 2
          weight: 80
        - id: ap-northeast-1
          name: Tokyo
          priority: 3
          weight: 60
          
    # 欧洲地区
    eu:
      name: Europe
      datacenters:
        - id: eu-west-1
          name: Ireland
          priority: 1
          weight: 100
        - id: eu-central-1
          name: Frankfurt
          priority: 2
          weight: 80
        - id: eu-west-2
          name: London
          priority: 3
          weight: 60
          
    # 北美地区
    na:
      name: North America
      datacenters:
        - id: us-east-1
          name: Virginia
          priority: 1
          weight: 100
        - id: us-west-1
          name: California
          priority: 2
          weight: 80
        - id: us-west-2
          name: Oregon
          priority: 3
          weight: 60
          
  # 路由策略
  routing:
    # 就近路由
    proximity:
      enabled: true
      max-latency-ms: 100
      fallback-strategy: ROUND_ROBIN
      
    # 故障转移
    failover:
      enabled: true
      retry-attempts: 3
      retry-delay-ms: 1000
      circuit-breaker:
        enabled: true
        failure-threshold: 5
        reset-timeout-ms: 60000
        
    # 流量分配
    traffic:
      strategy: WEIGHTED_ROUND_ROBIN
      health-check:
        enabled: true
        interval-seconds: 30
        timeout-seconds: 5
        unhealthy-threshold: 3
        healthy-threshold: 2
        
  # 负载均衡
  load-balancing:
    algorithm: LEAST_CONNECTIONS
    sticky-session:
      enabled: true
      cookie-name: REGION_AFFINITY
      max-age-seconds: 3600
      
    health-check:
      enabled: true
      path: /actuator/health
      interval-seconds: 30
      timeout-seconds: 5
      unhealthy-threshold: 3
      healthy-threshold: 2
      
  # 数据同步
  replication:
    enabled: true
    strategy: ASYNC
    batch-size: 1000
    interval-ms: 1000
    retry:
      max-attempts: 3
      backoff:
        initial-interval-ms: 1000
        multiplier: 2
        max-interval-ms: 10000
        
  # 监控指标
  metrics:
    enabled: true
    collection-interval-seconds: 60
    retention-days: 30
    export:
      prometheus:
        enabled: true
        path: /actuator/prometheus
      datadog:
        enabled: false
      elastic:
        enabled: false 