security:
  # 密码策略
  password:
    min-length: 12
    require-uppercase: true
    require-lowercase: true
    require-numbers: true
    require-special-chars: true
    max-age-days: 90
    history-size: 5
    max-attempts: 5
    lockout-duration-minutes: 30
    
  # 会话策略
  session:
    max-sessions-per-user: 3
    session-timeout-minutes: 30
    remember-me-days: 30
    idle-timeout-minutes: 15
    force-logout-on-password-change: true
    
  # 认证策略
  authentication:
    # JWT配置
    jwt:
      issuer: helix.com
      audience: dove-auth-service
      expiration-minutes: 60
      refresh-token-validity-days: 30
      
    # MFA配置
    mfa:
      enabled: true
      type: TOTP
      issuer: Helix
      digits: 6
      period: 30
      algorithm: SHA1
      
    # 社交登录配置
    social:
      providers:
        - name: google
          enabled: true
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
        - name: github
          enabled: true
          client-id: ${GITHUB_CLIENT_ID}
          client-secret: ${GITHUB_CLIENT_SECRET}
          
  # 授权策略
  authorization:
    default-roles:
      - ROLE_USER
    admin-roles:
      - ROLE_ADMIN
      - ROLE_SUPER_ADMIN
    permission-mapping:
      ROLE_USER:
        - read:profile
        - update:profile
      ROLE_ADMIN:
        - read:users
        - create:users
        - update:users
        - delete:users
      ROLE_SUPER_ADMIN:
        - "*"
        
  # 安全控制
  controls:
    cors:
      allowed-origins: 
        - https://*.helix.com
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      max-age: 3600
      
    csrf:
      enabled: true
      exclude-paths:
        - /api/v1/auth/**
        - /api/v1/oauth/**
        
    rate-limiting:
      login:
        max-attempts: 5
        window-minutes: 15
      password-reset:
        max-attempts: 3
        window-minutes: 60
        
  # 审计日志
  audit:
    enabled: true
    log-login-attempts: true
    log-admin-actions: true
    retention-days: 90 