system:
  # 系统基础配置
  basic:
    version: 1.0.0
    name: Dove Auth Service
    description: Authentication and Authorization Service
    maintainer: team@helix.com
    
  # 性能配置
  performance:
    # 线程池配置
    thread-pool:
      core-size: 50
      max-size: 200
      queue-capacity: 1000
      keep-alive-seconds: 60
    
    # 连接池配置
    connection-pool:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      
    # 缓存配置
    cache:
      default-ttl: 3600
      max-size: 10000
      
  # 功能开关
  features:
    mfa-enabled: true
    social-login-enabled: true
    password-policy-enabled: true
    session-control-enabled: true
    
  # 监控配置
  monitoring:
    metrics-enabled: true
    tracing-enabled: true
    logging-level: INFO
    
  # 限流配置
  rate-limit:
    enabled: true
    default-limit: 1000
    burst: 100
    
  # 熔断配置
  circuit-breaker:
    enabled: true
    failure-rate-threshold: 50
    wait-duration-in-open-state: 60000
    ring-buffer-size-in-half-open-state: 10
    ring-buffer-size-in-closed-state: 100 