server:
  port: 9000
  servlet:
    context-path: /auth

spring:
  application:
    name: dove-auth
  
  # 数据源配置
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dove_auth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  
  # 安全配置
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret

# Nacos配置
nacos:
  discovery:
    server-addr: localhost:8848
    namespace: dove
  config:
    server-addr: ${nacos.discovery.server-addr}
    namespace: ${nacos.discovery.namespace}
    file-extension: yaml

# Sentinel配置
sentinel:
  transport:
    dashboard: localhost:8080
  datasource:
    ds1:
      nacos:
        server-addr: ${nacos.config.server-addr}
        dataId: ${spring.application.name}-sentinel
        groupId: DEFAULT_GROUP
        rule-type: flow

# Feign配置
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# 日志配置
logging:
  level:
    root: INFO
    com.dove: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

# 应用自定义配置
dove:
  auth:
    # Token配置
    token:
      secret: your-jwt-secret-key
      access-token-validity: 3600
      refresh-token-validity: 86400
    # 安全配置
    security:
      password-strength: HIGH
      max-login-attempts: 5
      lock-duration: 300
      remember-me-key: your-remember-me-key
      remember-me-validity: 1209600
    # 验证码配置
    captcha:
      enabled: true
      type: math
      length: 4
      expire: 60
      width: 160
      height: 60
    # 第三方登录配置
    social:
      wechat:
        app-id: your-wechat-app-id
        app-secret: your-wechat-app-secret
      dingtalk:
        app-id: your-dingtalk-app-id
        app-secret: your-dingtalk-app-secret 