server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: dove-auth
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        file-extension: yml
  datasource:
    url: jdbc:postgresql://localhost:5432/dove_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 86400
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID:}
          client-secret: ${GOOGLE_CLIENT_SECRET:}
          scope:
            - email
            - profile

auth:
  server:
    issuer: http://localhost:8081
    support-refresh-token: true
    reuse-refresh-token: false

saml:
  okta:
    metadata-url: ${OKTA_METADATA_URL:}
    entity-id: ${OKTA_ENTITY_ID:}
    acs-url: ${OKTA_ACS_URL:}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    com.helix.dove: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO 