server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: dove-auth-service
  
  # 数据库配置
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dove_auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  # Cloud配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dove
      config:
        server-addr: localhost:8848
        namespace: dove
        file-extension: yaml
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

  # 国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.helix.dove.auth.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: your-secret-key
  expiration: 7200000  # 2小时
  refresh-expiration: 604800000  # 7天

# 安全配置
security:
  ignore-urls:
    - /auth/login
    - /auth/register
    - /auth/forgot-password
    - /auth/reset-password
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    root: INFO
    com.helix.dove: DEBUG
  file:
    name: logs/dove-auth-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30 