cache:
  local:
    caffeine:
      initial-capacity: 100
      maximum-size: 10000
      expire-after-write: 5m
      record-stats: true
  
  distributed:
    redis:
      mode: standalone
      nodes: ${REDIS_NODES:localhost:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
      timeout: 5000
      command-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000

  route:
    ttl: 300
    max-size: 1000
    eviction-policy: LRU

  predicate:
    ttl: 300
    max-size: 500
    eviction-policy: LRU

  filter:
    ttl: 300
    max-size: 500
    eviction-policy: LRU

  metrics:
    enabled: true
    log-interval: 60
    export-jmx: true