circuit-breaker:
  default:
    sliding-window-size: 100
    sliding-window-type: COUNT_BASED
    minimum-number-of-calls: 10
    failure-rate-threshold: 50
    wait-duration-in-open-state: 60s
    permitted-number-of-calls-in-half-open-state: 10
    slow-call-rate-threshold: 100
    slow-call-duration-threshold: 60s
    record-exceptions:
      - java.io.IOException
      - java.net.ConnectException
    ignore-exceptions:
      - org.springframework.web.client.HttpClientErrorException
    automatic-transition-from-open-to-half-open-enabled: true

  instances:
    user-service:
      base-config: default
      sliding-window-size: 50
      failure-rate-threshold: 30
    
    order-service:
      base-config: default
      sliding-window-size: 80
      failure-rate-threshold: 40
    
    product-service:
      base-config: default
      sliding-window-size: 120
      failure-rate-threshold: 60

  metrics:
    enabled: true
    tags:
      application: dove-api-gateway
    export:
      prometheus:
        enabled: true