monitoring:
  enabled: true
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: 1m
      jmx:
        enabled: true
    tags:
      application: dove-api-gateway
      environment: ${ENVIRONMENT:dev}

  tracing:
    enabled: true
    type: zipkin
    sample-rate: 0.1
    zipkin:
      base-url: ${ZIPKIN_URL:http://localhost:9411}
      service-name: dove-api-gateway

  logging:
    level: INFO
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file:
      enabled: true
      path: logs/dove-api-gateway.log
      max-size: 10MB
      max-history: 7

  health:
    enabled: true
    show-details: when_authorized
    probes:
      liveness:
        enabled: true
        initial-delay: 10s
        period: 30s
      readiness:
        enabled: true
        initial-delay: 20s
        period: 30s

  alerts:
    enabled: true
    endpoints:
      - type: slack
        url: ${SLACK_WEBHOOK_URL:}
      - type: email
        to: ${ALERT_EMAIL:}